### PR TITLE
Stedders

### LINKED ISSUE #7: Include tests to the python program that can be executed by github workflow
## Current Behaviour
Execution of the python program in the github workflow will fail.

## Changes Requested
Include tests in the python program.
Setup workflow to execute these tests.

### PR DESCRIPTION
**Pull request by Stedders**
### 2. Description
Added a first pass pytest test and github workflow action to test code on push. As mentioned in #7 comments, this could be improved and worth reviewing.

### 3. Fill in checklist by marking [x]

- [ x] I've read the CONTRIBUTING.md
- [ x] I was assigned to this issue
- [ ] My code is formatted using required linting
- [ x] I've run my code locally and checked it works

no linting due to current code structure, changes required for flake8 to pass

### CODE REVIEW

**Comment by funbeedev** [comment]
@Stedders 
Thanks for finding a way to run some sort of test on this app.  From my understanding, your test program will create the repo files locally and verify they exists through the asserts. And unless I'm missing something, but how are all functions from automate-git.py able to run through the test without needing the create a real repository on Github? What exactly is monkeypatch doing?

I'm not that familiar with using pytest so have to spend more time understanding all parts of this test.
Would you also add some comments to test_automate_git.py?

On the linting error, you mentioned in the issue:
> As it stands I won't create the PR as the code fails flake8 linting (start_program_flow() is not in the linting scope as it is checking the code statically), this can be rectified but would need the config.ini file in the route of the directory to be manipulated during running, which feels wrong.

I dont fully get how the config.ini is related to why the linting is failing, can you explain further please?

Thanks!

**Comment by Stedders** [comment]
Long response so bear with me...

> Thanks for finding a way to run some sort of test on this app. From my understanding, your test program will create the repo files locally and verify they exists through the asserts.

Not a problem, happy to help. Correct, the code creates a local config.ini  in the test directory and then executes the program in using the test directory as its working root.

>but how are all functions from automate-git.py able to run through the test without needing the create a real repository on Github? What exactly is monkeypatch doing?

This is the [monkeypatch](https://docs.pytest.org/en/stable/monkeypatch.html) magic - it allows you to [mock](https://stackoverflow.com/questions/2665812/what-is-mocking/2666006#2666006) a function to do something in a specific manner. The thought process being that we don't need/want to test an external library, we trust their developers to test their code and for it to work, we do want to check the behaviour of our code with a specific response.

In the test I mock the json.loads() method and replace it with mock_json_loads(), which simply returns a data structure representing the response from GitHub. 

So this code in automate-git.py...

```python
# convert from completed process for easier parsing
response_json = json.loads(response.stdout.decode("utf-8"))
```
...gets patched...

```python
monkeypatch.setattr(json, 'loads', mock_json_loads)
```
...and runs this function from test_automate_git.py when `loads()` is called...

```python
def mock_json_loads(response_output):
    return [{'name': 'test_repo', 'html_url': 'http://github.com/fake_repo'}]
```

This could be extended to return corrupted data, 404, network errors, etc... to test specific exception handling.

> Would you also add some comments to test_automate_git.py?

Yes, apologies - my bad.

> I dont fully get how the config.ini is related to why the linting is failing, can you explain further please?

Of course...this is somewhat convoluted and the point I was making was about editing a project asset during the testing.

The linting is failing because the linter can't find the function `start_program_flow()` in the test file, the reason is that it is not being loaded until execution time using `execfile('../automate-git.py')` which is a nasty way of loading the functions.

To load it in a way that the linter recognizes with the current design, we would need the test to run in the root folder (and the program should probably be renamed `automate_git.py` so it can be imported, as mentioned in the [project structure guide](https://docs.python-guide.org/writing/structure/#modules)*).

If the test runs in the root of the project then it will either load the empty config.ini file or the file will need to be edited in place, loaded and then reverted - if something goes wrong in this process you would have a dirty config file in the repo that is at risk of being committed :-1:.

_Amusingly, writing this made me think of a third option that is "less worse" than the above - we could monkeypatch the config.get() method to set the values. This process would result in lots of code being written in the test to work around the rigid design of the application._

My proposal is to add a config_file parameter to `start_program_flow()`, this can be set by default in the `__main__` , and then load the configuration their. This would allow multiple config files to be written and stored in the repo for testing and prevents the config.ini in the repo from being manipulated.

I hope I explained what was going through my :brain: clearly? :confused: 

Let me know your thoughts, I'll add the comments to the tests tomorrow.

Regards
Luke

_...this statement on the project structure page is not entirely true._
> However, using other characters (spaces or hyphens) in module names will prevent importing (- is the subtract operator).

This can be achieved with `__import__()` function or `importlib` module, but probably not a good idea.

**Comment by funbeedev** [comment]
@Stedders Thanks for your very detailed response! The test file makes a lot more sense to me now especially with the added comments :)

> The linting is failing because the linter can't find the function start_program_flow() in the test file, the reason is that it is not being loaded until execution time using execfile('../automate-git.py') which is a nasty way of loading the functions.

I see.. will have to find a way to sort that out for sure.

> To load it in a way that the linter recognizes with the current design, we would need the test to run in the root folder (and the program should probably be renamed automate_git.py so it can be imported, as mentioned in the project structure guide*).

Wow, I never would have known using '-' in the program name would cause a problem!

> My proposal is to add a config_file parameter to start_program_flow(), this can be set by default in the __main__ , and then load the configuration their. This would allow multiple config files to be written and stored in the repo for testing and prevents the config.ini in the repo from being manipulated.

Makes sense why we should pass the config file as a parameter.. I really need to think of how tests will be run when writing the program 😅 

> I hope I explained what was going through my brain clearly? confused

Great explanation. You've taught me quite a few things. Thanks again :)

When I make your suggested changes to sort out the linting error I'll merge the PR. Of course feel free also to change anything else on the repo if you wish!

**Comment by funbeedev** [comment]
@Stedders I made some commits to your PR. Can you review and check all is okay before i merge?!

By the way, I deleted the .gitignore as it didn't capture all files to ignore for me. will create a separate issue to tidy that up and to add instructions for running the test locally.

**Comment by Stedders** [comment]
Of course, I will take a look today.

**Comment by Stedders** [comment]
As it is, I think you can merge it in.

You should consider testing each function separately, but now we have a base testing script it will make managing changes a lot easier.

**Comment by funbeedev** [comment]
@Stedders Agreed, still room for improvement but this is certainly a good start. Thanks for your help with this!

**Pull request merged**
